package it.water.company.repository;

import it.water.company.api.CompanyRepository;
import it.water.company.model.Company;
import it.water.core.interceptors.annotations.FrameworkComponent;
import it.water.repository.jpa.WaterJpaRepositoryImpl;

/**
 * @Generated by Water Generator
 * Repository Class for Company entity.
 */
@FrameworkComponent
public class CompanyRepositoryImpl extends WaterJpaRepositoryImpl<Company> implements CompanyRepository {

    private static final String COMPANY_PERSISTENCE_UNIT = "company-persistence-unit";

    public CompanyRepositoryImpl() {
        super(Company.class, COMPANY_PERSISTENCE_UNIT);
    }

}
